name: Automate Task with Google Cloud Service Account

on:
  workflow_dispatch:  # This line allows manual triggering
  schedule:
    - cron: '0 16 * * *' # Runs at 16:00 UTC, which is 23:00 in Bangkok
    #- cron: '15 16 * * *' # Runs at 16:15 UTC, which is 23:15 in Bangkok

jobs:
  automate-task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib pandas requests

      - name: Decode GCP Service Account Key
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > gcp_service_account.json
        shell: bash

      - name: Run Script
        run: |
          python fetch_data.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $PWD/gcp_service_account.json